# -*- coding: utf-8 -*-
{
    'name':'LDS Device',
    'summary': """Quản lý thiết bị LDS""",
    'version': '0.1',
    'description': """Quản lý thiết bị LDS""",
    'author': 'Lv Quý',
    'company': 'LDS',
    'website': 'http://tinyERP.net',
    'category': 'LDS Device',
    'depends': ['base', 'report','mail'],
    'license': 'AGPL-3',
    'data': [
        'views/view.xml',
        'views/adapter_mat.xml',
        'views/bo_phan.xml',
        'views/line_thiet_bi.xml',
        'views/nguoi_bao_quan.xml',
        'views/nha_cung_cap.xml',
        'views/nhat_ky.xml',
        'views/tai_khoan.xml',
        'views/thiet_bi.xml',
        'views/thuoc_tinh.xml',
        'views/os_pc_laptop.xml',
        'views/email_noi.xml',
        'views/email_ngoai.xml',
        'views/skype.xml',
        'views/server.xml',
        'views/log_check.xml',
        'views/line_check.xml',
        'views/xuong_may.xml',
        'views/bao_cao.xml',
        # 'views/baotri.xml',
        # 'views/line_baotri.xml',
        'data/ir_seq_data.xml',
        'data/data_lds.xml',
        'report/label_device.xml',
        'report/view.xml',
        'report/email_noi.xml',
        'report/email_ngoai.xml',
        'report/server.xml',
        'report/skype.xml',
        'report/bao_cao.xml'
    ],
    'css': [],
	'qweb': [
	],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}